import { F1Team } from '@libs/models/f1-team.model';

export const F1_TEAMS: F1Team[] = [
  {
    id: 1,
    name: 'Ferrari',
    originCountry: 'Italy',
    originCountryFlag: 'it',
    headquarters: 'Maranello, Italy',
    headquartersFlag: 'it',
    foundedYear: 1950,
    grandPrixWins: 248,
    constructorChampionships: 16,
  },
  {
    id: 2,
    name: 'McLaren',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Woking, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1963,
    grandPrixWins: 203,
    constructorChampionships: 10,
  },
  {
    id: 3,
    name: 'Mercedes',
    originCountry: 'Germany',
    originCountryFlag: 'de',
    headquarters: 'Brackley, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1954,
    grandPrixWins: 125,
    constructorChampionships: 8,
  },
  {
    id: 4,
    name: 'Red Bull Racing',
    originCountry: 'Austria',
    originCountryFlag: 'at',
    headquarters: 'Milton Keynes, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 2005,
    grandPrixWins: 130,
    constructorChampionships: 6,
  },
  {
    id: 5,
    name: 'Williams',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Grove, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1977,
    grandPrixWins: 114,
    constructorChampionships: 9,
  },
  {
    id: 6,
    name: 'Alpine',
    originCountry: 'France',
    originCountryFlag: 'fr',
    headquarters: 'Enstone, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 2021,
    grandPrixWins: 1,
    constructorChampionships: 0,
  },
  {
    id: 7,
    name: 'Aston Martin',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Silverstone, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 2021,
    grandPrixWins: 0,
    constructorChampionships: 0,
  },
  {
    id: 8,
    name: 'Haas',
    originCountry: 'United States',
    originCountryFlag: 'us',
    headquarters: 'Kannapolis, United States',
    headquartersFlag: 'us',
    foundedYear: 2016,
    grandPrixWins: 0,
    constructorChampionships: 0,
  },
  {
    id: 9,
    name: 'Kick Sauber',
    originCountry: 'Switzerland',
    originCountryFlag: 'ch',
    headquarters: 'Hinwil, Switzerland',
    headquartersFlag: 'ch',
    foundedYear: 1993,
    grandPrixWins: 0,
    constructorChampionships: 0,
  },
  {
    id: 10,
    name: 'Racing Bulls',
    originCountry: 'Italy',
    originCountryFlag: 'it',
    headquarters: 'Faenza, Italy',
    headquartersFlag: 'it',
    foundedYear: 2024,
    grandPrixWins: 0,
    constructorChampionships: 0,
  },
  {
    id: 11,
    name: 'Alpha Tauri',
    originCountry: 'Italy',
    originCountryFlag: 'it',
    headquarters: 'Faenza, Italy',
    headquartersFlag: 'it',
    foundedYear: 2006,
    grandPrixWins: 1,
    constructorChampionships: 0,
  },
  {
    id: 12,
    name: 'Alfa Romeo',
    originCountry: 'Italy',
    originCountryFlag: 'it',
    headquarters: 'Hinwil, Switzerland',
    headquartersFlag: 'ch',
    foundedYear: 2019,
    grandPrixWins: 0,
    constructorChampionships: 0,
  },
  {
    id: 13,
    name: 'Lotus',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Hethel, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1952,
    grandPrixWins: 81,
    constructorChampionships: 7,
  },
  {
    id: 14,
    name: 'Renault',
    originCountry: 'France',
    originCountryFlag: 'fr',
    headquarters: 'Enstone, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1977,
    grandPrixWins: 35,
    constructorChampionships: 2,
  },
  {
    id: 15,
    name: 'Brabham',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Chessington, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1962,
    grandPrixWins: 35,
    constructorChampionships: 2,
    logo: 'assets/images/logos/Brabham.png',
  },
  {
    id: 16,
    name: 'Cooper',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Surbiton, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1946,
    grandPrixWins: 16,
    constructorChampionships: 2,
    logo: 'assets/images/logos/Cooper.png',
  },
  {
    id: 17,
    name: 'BRM',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Bourne, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1945,
    grandPrixWins: 17,
    constructorChampionships: 1,
    logo: 'assets/images/logos/BRM.png',
  },
  {
    id: 18,
    name: 'Tyrrell',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Ockham, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1968,
    grandPrixWins: 23,
    constructorChampionships: 1,
    logo: 'assets/images/logos/Tyrrell.png',
  },
  {
    id: 19,
    name: 'Matra',
    originCountry: 'France',
    originCountryFlag: 'fr',
    headquarters: 'Vélizy-Villacoublay, France',
    headquartersFlag: 'fr',
    foundedYear: 1966,
    grandPrixWins: 12,
    constructorChampionships: 1,
    logo: 'assets/images/logos/Matra.png',
  },
  {
    id: 20,
    name: 'Vanwall',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Acton, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1954,
    grandPrixWins: 9,
    constructorChampionships: 1,
    logo: 'assets/images/logos/Vanwall.png',
  },
  {
    id: 21,
    name: 'Benetton',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Enstone, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1986,
    grandPrixWins: 27,
    constructorChampionships: 1,
    logo: 'assets/images/logos/Benetton.png',
  },
];
