import { RacerInfo } from '../../interfaces';

export const RACERS_INFO: RacerInfo[] = [
  {
    id: 1,
    identifier: 'NinoFarina',
    name: 'Nino Farina',
    country: 'Italy',
    flag: 'it',
    wins: 5,
    placeOfBirth: 'Turin, Italy',
    dateOfBirth: '30 October 1906',
    dateOfDeath: '30 June 1966',
    f1Teams: ['Alfa Romeo', 'Ferrari'],
  },
  {
    id: 2,
    identifier: 'JuanManuelFangio',
    name: 'Juan Manuel Fangio',
    country: 'Argentina',
    flag: 'ar',
    wins: 24,
    placeOfBirth: 'Balcarce, Argentina',
    dateOfBirth: '24 June 1911',
    dateOfDeath: '17 July 1995',
    f1Teams: ['Alfa Romeo', 'Maserati', 'Mercedes', 'Ferrari'],
  },
  {
    id: 3,
    identifier: 'AlbertoAscari',
    name: 'Alberto Ascari',
    country: 'Italy',
    flag: 'it',
    wins: 13,
    placeOfBirth: 'Milan, Italy',
    dateOfBirth: '13 July 1918',
    dateOfDeath: '26 May 1955',
    f1Teams: ['Ferrari', 'Maserati', 'Lancia'],
  },
  {
    id: 4,
    identifier: 'MikeHawthorn',
    name: 'Mike Hawthorn',
    country: 'United Kingdom',
    flag: 'gb',
    wins: 3,
    placeOfBirth: 'Mexborough, United Kingdom',
    dateOfBirth: '10 April 1929',
    dateOfDeath: '22 January 1959',
    f1Teams: ['Ferrari', 'Cooper', 'Vanwall', 'BRM', 'Maserati'],
  },
  {
    id: 5,
    identifier: 'JackBrabham',
    name: 'Jack Brabham',
    country: 'Australia',
    flag: 'au',
    wins: 14,
    placeOfBirth: 'Hurstville, Australia',
    dateOfBirth: '2 April 1926',
    dateOfDeath: '19 May 2014',
    f1Teams: ['Cooper', 'Brabham', 'Lotus', 'Maserati'],
  },
  {
    id: 6,
    identifier: 'PhilHill',
    name: 'Phil Hill',
    country: 'United States',
    flag: 'us',
    wins: 3,
    placeOfBirth: 'Miami, United States',
    dateOfBirth: '20 April 1927',
    dateOfDeath: '28 August 2008',
    f1Teams: ['Ferrari', 'Maserati', 'Cooper', 'Lotus'],
  },
  {
    id: 7,
    identifier: 'GrahamHill',
    name: 'Graham Hill',
    country: 'United Kingdom',
    flag: 'gb',
    wins: 14,
    placeOfBirth: 'Hampstead, United Kingdom',
    dateOfBirth: '15 February 1929',
    dateOfDeath: '29 November 1975',
    f1Teams: ['Lotus', 'BRM', 'Brabham'],
  },
  {
    id: 8,
    identifier: 'JimClark',
    name: 'Jim Clark',
    country: 'United Kingdom',
    flag: 'gb',
    wins: 25,
    placeOfBirth: 'Kilmany, Scotland',
    dateOfBirth: '4 March 1936',
    dateOfDeath: '7 April 1968',
    f1Teams: ['Lotus'],
  },
  {
    id: 9,
    identifier: 'JohnSurtees',
    name: 'John Surtees',
    country: 'United Kingdom',
    flag: 'gb',
    wins: 6,
    placeOfBirth: 'Tatsfield, United Kingdom',
    dateOfBirth: '11 February 1934',
    dateOfDeath: '10 March 2017',
    f1Teams: ['Ferrari', 'Honda', 'Cooper'],
  },
  {
    id: 10,
    identifier: 'DennyHulme',
    name: 'Denny Hulme',
    country: 'New Zealand',
    flag: 'nz',
    wins: 8,
    placeOfBirth: 'Motueka, New Zealand',
    dateOfBirth: '18 June 1936',
    dateOfDeath: '4 October 1992',
    f1Teams: ['Brabham', 'McLaren'],
  },
  {
    id: 11,
    identifier: 'JackieStewart',
    name: 'Jackie Stewart',
    country: 'United Kingdom',
    flag: 'gb',
    wins: 27,
    placeOfBirth: 'Milton, United Kingdom',
    dateOfBirth: '11 June 1939',
    dateOfDeath: '',
    f1Teams: ['BRM', 'Matra', 'Tyrrell'],
  },
  {
    id: 12,
    identifier: 'JochenRindt',
    name: 'Jochen Rindt',
    country: 'Austria',
    flag: 'at',
    wins: 6,
    placeOfBirth: 'Mainz, Germany',
    dateOfBirth: '18 April 1942',
    dateOfDeath: '5 September 1970',
    f1Teams: ['Cooper', 'Brabham', 'Lotus'],
  },
  {
    id: 13,
    identifier: 'EmersonFittipaldi',
    name: 'Emerson Fittipaldi',
    country: 'Brazil',
    flag: 'br',
    wins: 14,
    placeOfBirth: 'São Paulo, Brazil',
    dateOfBirth: '12 December 1946',
    dateOfDeath: '',
    f1Teams: ['Lotus', 'McLaren', 'Fittipaldi'],
  },
  {
    id: 14,
    identifier: 'NikiLauda',
    name: 'Niki Lauda',
    country: 'Austria',
    flag: 'at',
    wins: 25,
    placeOfBirth: 'Vienna, Austria',
    dateOfBirth: '22 February 1949',
    dateOfDeath: '20 May 2019',
    f1Teams: ['March', 'BRM', 'Ferrari', 'Brabham', 'McLaren'],
  },
  {
    id: 15,
    identifier: 'JamesHunt',
    name: 'James Hunt',
    country: 'United Kingdom',
    flag: 'gb',
    wins: 10,
    placeOfBirth: 'Belmont, United Kingdom',
    dateOfBirth: '29 August 1947',
    dateOfDeath: '15 June 1993',
    f1Teams: ['Hesketh', 'McLaren', 'Wolf'],
  },
  {
    id: 16,
    identifier: 'MarioAndretti',
    name: 'Mario Andretti',
    country: 'United States',
    flag: 'us',
    wins: 12,
    placeOfBirth: 'Montona, Italy',
    dateOfBirth: '28 February 1940',
    dateOfDeath: '',
    f1Teams: [
      'Lotus',
      'March',
      'Ferrari',
      'Parnelli',
      'Alfa Romeo',
      'Williams',
    ],
  },
  {
    id: 17,
    identifier: 'JodyScheckter',
    name: 'Jody Scheckter',
    country: 'South Africa',
    flag: 'za',
    wins: 10,
    placeOfBirth: 'East London, South Africa',
    dateOfBirth: '29 January 1950',
    dateOfDeath: '',
    f1Teams: ['McLaren', 'Tyrrell', 'Wolf', 'Ferrari'],
  },
  {
    id: 18,
    identifier: 'AlanJones',
    name: 'Alan Jones',
    country: 'Australia',
    flag: 'au',
    wins: 12,
    placeOfBirth: 'Melbourne, Australia',
    dateOfBirth: '2 November 1946',
    dateOfDeath: '',
    f1Teams: ['Williams', 'Shadow'],
  },
  {
    id: 19,
    identifier: 'NelsonPiquet',
    name: 'Nelson Piquet',
    country: 'Brazil',
    flag: 'br',
    wins: 23,
    placeOfBirth: 'Rio de Janeiro, Brazil',
    dateOfBirth: '17 August 1952',
    dateOfDeath: '',
    f1Teams: ['Brabham', 'Williams', 'Lotus', 'Benetton'],
  },
  {
    id: 20,
    identifier: 'KekeRosberg',
    name: 'Keke Rosberg',
    country: 'Finland',
    flag: 'fi',
    wins: 5,
    placeOfBirth: 'Solna, Sweden',
    dateOfBirth: '6 December 1948',
    dateOfDeath: '',
    f1Teams: ['Williams', 'Fittipaldi', 'McLaren'],
  },
  {
    id: 21,
    identifier: 'AlainProst',
    name: 'Alain Prost',
    country: 'France',
    flag: 'fr',
    wins: 51,
    placeOfBirth: 'Lorette, France',
    dateOfBirth: '24 February 1955',
    dateOfDeath: '',
    f1Teams: ['McLaren', 'Renault', 'Ferrari', 'Williams'],
  },
  {
    id: 22,
    identifier: 'AyrtonSenna',
    name: 'Ayrton Senna',
    country: 'Brazil',
    flag: 'br',
    wins: 41,
    placeOfBirth: 'São Paulo, Brazil',
    dateOfBirth: '21 March 1960',
    dateOfDeath: '1 May 1994',
    f1Teams: ['Toleman', 'Lotus', 'McLaren', 'Williams'],
  },
  {
    id: 23,
    identifier: 'NigelMansell',
    name: 'Nigel Mansell',
    country: 'United Kingdom',
    flag: 'gb',
    wins: 31,
    placeOfBirth: 'Upton-upon-Severn, United Kingdom',
    dateOfBirth: '8 August 1953',
    dateOfDeath: '',
    f1Teams: ['Lotus', 'Williams', 'Ferrari', 'McLaren'],
  },
  {
    id: 24,
    identifier: 'MichaelSchumacher',
    name: 'Michael Schumacher',
    country: 'Germany',
    flag: 'de',
    wins: 91,
    placeOfBirth: 'Hürth, Germany',
    dateOfBirth: '3 January 1969',
    dateOfDeath: '',
    f1Teams: ['Jordan', 'Benetton', 'Ferrari', 'Mercedes'],
  },
  {
    id: 25,
    identifier: 'DamonHill',
    name: 'Damon Hill',
    country: 'United Kingdom',
    flag: 'gb',
    wins: 22,
    placeOfBirth: 'Hampstead, United Kingdom',
    dateOfBirth: '17 September 1960',
    dateOfDeath: '',
    f1Teams: ['Brabham', 'Williams', 'Arrows', 'Jordan'],
  },
  {
    id: 26,
    identifier: 'JacquesVilleneuve',
    name: 'Jacques Villeneuve',
    country: 'Canada',
    flag: 'ca',
    wins: 11,
    placeOfBirth: 'Saint-Jean-sur-Richelieu, Canada',
    dateOfBirth: '9 April 1971',
    dateOfDeath: '',
    f1Teams: ['Williams', 'BAR', 'Renault', 'Sauber'],
  },
  {
    id: 27,
    identifier: 'MikaHakkinen',
    name: 'Mika Hakkinen',
    country: 'Finland',
    flag: 'fi',
    wins: 20,
    placeOfBirth: 'Vantaa, Finland',
    dateOfBirth: '28 September 1968',
    dateOfDeath: '',
    f1Teams: ['Lotus', 'McLaren'],
  },
  {
    id: 28,
    identifier: 'FernandoAlonso',
    name: 'Fernando Alonso',
    country: 'Spain',
    flag: 'es',
    wins: 32,
    placeOfBirth: 'Oviedo, Spain',
    dateOfBirth: '29 July 1981',
    dateOfDeath: '',
    f1Teams: ['Minardi', 'Renault', 'McLaren', 'Ferrari', 'Alpine'],
  },
  {
    id: 29,
    identifier: 'KimiRaikkonen',
    name: 'Kimi Raikkonen',
    country: 'Finland',
    flag: 'fi',
    wins: 21,
    placeOfBirth: 'Espoo, Finland',
    dateOfBirth: '17 October 1979',
    dateOfDeath: '',
    f1Teams: ['Sauber', 'McLaren', 'Ferrari', 'Lotus', 'Alfa Romeo'],
  },
  {
    id: 30,
    identifier: 'LewisHamilton',
    name: 'Lewis Hamilton',
    country: 'United Kingdom',
    flag: 'gb',
    wins: 100,
    placeOfBirth: 'Stevenage, United Kingdom',
    dateOfBirth: '7 January 1985',
    dateOfDeath: '',
    f1Teams: ['McLaren', 'Mercedes', 'Ferrari'],
  },
  {
    id: 31,
    identifier: 'JensonButton',
    name: 'Jenson Button',
    country: 'United Kingdom',
    flag: 'gb',
    wins: 15,
    placeOfBirth: 'Frome, United Kingdom',
    dateOfBirth: '19 January 1980',
    dateOfDeath: '',
    f1Teams: [
      'Williams',
      'Benetton',
      'Renault',
      'BAR',
      'Honda',
      'Brawn GP',
      'McLaren',
    ],
  },
  {
    id: 32,
    identifier: 'SebastianVettel',
    name: 'Sebastian Vettel',
    country: 'Germany',
    flag: 'de',
    wins: 53,
    placeOfBirth: 'Heppenheim, Germany',
    dateOfBirth: '3 July 1987',
    dateOfDeath: '',
    f1Teams: ['Sauber', 'Toro Rosso', 'Red Bull', 'Ferrari', 'Aston Martin'],
  },
  {
    id: 33,
    identifier: 'NicoRosberg',
    name: 'Nico Rosberg',
    country: 'Germany',
    flag: 'de',
    wins: 23,
    placeOfBirth: 'Wiesbaden, Germany',
    dateOfBirth: '27 June 1985',
    dateOfDeath: '',
    f1Teams: ['Williams', 'Mercedes'],
  },
  {
    id: 34,
    identifier: 'MaxVerstappen',
    name: 'Max Verstappen',
    country: 'Netherlands',
    flag: 'nl',
    wins: 20,
    placeOfBirth: 'Hasselt, Belgium',
    dateOfBirth: '30 September 1997',
    dateOfDeath: '',
    f1Teams: ['Toro Rosso', 'Red Bull'],
  },
];
