export const HALL_OF_FAME = [
  { id: 1, name: 'Nino Farina', country: 'Italy', winDate: '1950', flag: 'it' },
  {
    id: 2,
    name: 'Juan Manuel Fangio',
    country: 'Argentina',
    winDate: '1951, 1954, 1955, 1956, 1957',
    flag: 'ar',
  },
  {
    id: 3,
    name: 'Alberto Ascari',
    country: 'Italy',
    winDate: '1952, 1953',
    flag: 'it',
  },
  {
    id: 4,
    name: 'Mike Hawthorn',
    country: 'United Kingdom',
    winDate: '1958',
    flag: 'gb',
  },
  {
    id: 5,
    name: 'Jack Brabham',
    country: 'Australia',
    winDate: '1959, 1960, 1966',
    flag: 'au',
  },
  {
    id: 6,
    name: 'Phil Hill',
    country: 'United States',
    winDate: '1961',
    flag: 'us',
  },
  {
    id: 7,
    name: 'Graham Hill',
    country: 'United Kingdom',
    winDate: '1962, 1968',
    flag: 'gb',
  },
  {
    id: 8,
    name: 'Jim Clark',
    country: 'United Kingdom',
    winDate: '1963, 1965',
    flag: 'gb',
  },
  {
    id: 9,
    name: 'John Surtees',
    country: 'United Kingdom',
    winDate: '1964',
    flag: 'gb',
  },
  {
    id: 10,
    name: 'Denny Hulme',
    country: 'New Zealand',
    winDate: '1967',
    flag: 'nz',
  },
  {
    id: 11,
    name: 'Jackie Stewart',
    country: 'United Kingdom',
    winDate: '1969, 1971, 1973',
    flag: 'gb',
  },
  {
    id: 12,
    name: 'Jochen Rindt',
    country: 'Austria',
    winDate: '1970',
    flag: 'at',
  },
  {
    id: 13,
    name: 'Emerson Fittipaldi',
    country: 'Brazil',
    winDate: '1972, 1974',
    flag: 'br',
  },
  {
    id: 14,
    name: 'Niki Lauda',
    country: 'Austria',
    winDate: '1975, 1977, 1984',
    flag: 'at',
  },
  {
    id: 15,
    name: 'James Hunt',
    country: 'United Kingdom',
    winDate: '1976',
    flag: 'gb',
  },
  {
    id: 16,
    name: 'Mario Andretti',
    country: 'United States',
    winDate: '1978',
    flag: 'us',
  },
  {
    id: 17,
    name: 'Jody Scheckter',
    country: 'South Africa',
    winDate: '1979',
    flag: 'za',
  },
  {
    id: 18,
    name: 'Alan Jones',
    country: 'Australia',
    winDate: '1980',
    flag: 'au',
  },
  {
    id: 19,
    name: 'Nelson Piquet',
    country: 'Brazil',
    winDate: '1981, 1983, 1987',
    flag: 'br',
  },
  {
    id: 20,
    name: 'Keke Rosberg',
    country: 'Finland',
    winDate: '1982',
    flag: 'fi',
  },
  {
    id: 21,
    name: 'Alain Prost',
    country: 'France',
    winDate: '1985, 1986, 1989, 1993',
    flag: 'fr',
  },
  {
    id: 22,
    name: 'Ayrton Senna',
    country: 'Brazil',
    winDate: '1988, 1990, 1991',
    flag: 'br',
  },
  {
    id: 23,
    name: 'Nigel Mansell',
    country: 'United Kingdom',
    winDate: '1992',
    flag: 'gb',
  },
  {
    id: 24,
    name: 'Michael Schumacher',
    country: 'Germany',
    winDate: '1994, 1995, 2000, 2001, 2002, 2003, 2004',
    flag: 'de',
  },
  {
    id: 25,
    name: 'Damon Hill',
    country: 'United Kingdom',
    winDate: '1996',
    flag: 'gb',
  },
  {
    id: 26,
    name: 'Jacques Villeneuve',
    country: 'Canada',
    winDate: '1997',
    flag: 'ca',
  },
  {
    id: 27,
    name: 'Mika Hakkinen',
    country: 'Finland',
    winDate: '1998, 1999',
    flag: 'fi',
  },
  {
    id: 28,
    name: 'Fernando Alonso',
    country: 'Spain',
    winDate: '2005, 2006',
    flag: 'es',
  },
  {
    id: 29,
    name: 'Kimi Raikkonen',
    country: 'Finland',
    winDate: '2007',
    flag: 'fi',
  },
  {
    id: 30,
    name: 'Lewis Hamilton',
    country: 'United Kingdom',
    winDate: '2008, 2014, 2015, 2017, 2018, 2019, 2020',
    flag: 'gb',
  },
  {
    id: 31,
    name: 'Jenson Button',
    country: 'United Kingdom',
    winDate: '2009',
    flag: 'gb',
  },
  {
    id: 32,
    name: 'Sebastian Vettel',
    country: 'Germany',
    winDate: '2010, 2011, 2012, 2013',
    flag: 'de',
  },
  {
    id: 33,
    name: 'Nico Rosberg',
    country: 'Germany',
    winDate: '2016',
    flag: 'de',
  },
  {
    id: 34,
    name: 'Max Verstappen',
    country: 'Netherlands',
    winDate: '2021, 2022, 2023, 2024',
    flag: 'nl',
  },
];
