import { TeamInfo } from '../../interfaces';

export const TEAMS_INFO: TeamInfo[] = [
  {
    id: 1,
    identifier: 'Ferrari',
    name: 'Ferrari',
    fullName: 'Scuderia Ferrari HP',
    base: 'Maranello, Italy',
    flag: 'it',
    teamChief: 'Frédéric Vasseur',
    technicalChief: 'Loic Serra/ Enrico Gualtieri',
    chassis: 'SF-25',
    powerUnit: 'Ferrari',
    firstTeamEntry: 1950,
    worldChampionships: 16,
    highestRaceFinish: '1 (x249)',
    polePositions: 253,
    fastestLaps: 263,
  },
  {
    id: 2,
    identifier: 'McLaren',
    name: 'McLaren',
    fullName: 'McLaren Formula 1 Team',
    base: 'Woking, United Kingdom',
    flag: 'gb',
    teamChief: 'Andrea Stella',
    technicalChief: 'Peret Prodromou / Neil Houldey',
    chassis: 'TBC',
    powerUnit: 'Mercedes',
    firstTeamEntry: 1963,
    worldChampionships: 8,
    highestRaceFinish: '1 (x183)',
    polePositions: 164,
    fastestLaps: 172,
  },
  {
    id: 3,
    identifier: 'Mercedes',
    name: 'Mercedes',
    fullName: 'Mercedes-AMG Petronas Formula One Team',
    base: 'Brackley, United Kingdom',
    flag: 'gb',
    teamChief: 'Toto Wolff',
    technicalChief: 'James Allison',
    chassis: 'W16',
    powerUnit: 'Mercedes',
    firstTeamEntry: 1954,
    worldChampionships: 8,
    highestRaceFinish: '1 (x125)',
    polePositions: 133,
    fastestLaps: 100,
  },
  {
    id: 4,
    identifier: 'RedBullRacing',
    name: 'Red Bull Racing',
    fullName: 'Oracle Red Bull Racing',
    base: 'Milton Keynes, United Kingdom',
    flag: 'gb',
    teamChief: 'Christian Horner',
    technicalChief: 'Pierre Wache',
    chassis: 'RB21',
    powerUnit: 'Honda RBPT',
    firstTeamEntry: 2005,
    worldChampionships: 5,
    highestRaceFinish: '1 (x92)',
    polePositions: 103,
    fastestLaps: 99,
  },
  {
    id: 5,
    identifier: 'Williams',
    name: 'Williams',
    fullName: 'Williams Racing',
    base: 'Grove, United Kingdom',
    flag: 'gb',
    teamChief: 'James Vowles',
    technicalChief: 'Pat Fry',
    chassis: 'FW47',
    powerUnit: 'Mercedes',
    firstTeamEntry: 1977,
    worldChampionships: 9,
    highestRaceFinish: '1 (x114)',
    polePositions: 128,
    fastestLaps: 133,
  },
  {
    id: 6,
    identifier: 'Alpine',
    name: 'Alpine',
    fullName: 'BWT Alpine Formula One Team',
    base: 'Enstone, United Kingdom',
    flag: 'gb',
    teamChief: 'Oliver Oakes',
    technicalChief: 'David Sanchez',
    chassis: 'A525',
    powerUnit: 'Renault',
    firstTeamEntry: 2021,
    worldChampionships: 0,
    highestRaceFinish: '1',
    polePositions: 20,
    fastestLaps: 16,
  },
  {
    id: 7,
    identifier: 'AstonMartin',
    name: 'Aston Martin',
    fullName: 'Aston Martin Aramco Formula One Team',
    base: 'Silverstone, United Kingdom',
    flag: 'gb',
    teamChief: 'Andy Cowell',
    technicalChief: 'Enrico Cardile',
    chassis: 'AMR25',
    powerUnit: 'Mercedes',
    firstTeamEntry: 2021,
    worldChampionships: 0,
    highestRaceFinish: '0',
    polePositions: 1,
    fastestLaps: 3,
  },
  {
    id: 8,
    identifier: 'Haas',
    name: 'Haas',
    fullName: 'MoneyGram Haas F1 Team',
    base: 'Kannapolis, United States',
    flag: 'us',
    teamChief: 'Ayao Komatsu',
    technicalChief: 'Andrea De Zordo',
    chassis: 'TBC',
    powerUnit: 'Ferrari',
    firstTeamEntry: 2016,
    worldChampionships: 0,
    highestRaceFinish: '0',
    polePositions: 1,
    fastestLaps: 3,
  },
  {
    id: 9,
    identifier: 'KickSauber',
    name: 'Kick Sauber',
    fullName: 'Stake F1 Team Kick Sauber',
    base: 'Hinwil, Switzerland',
    flag: 'ch',
    teamChief: 'Mattia Binotto',
    technicalChief: 'James Key',
    chassis: 'TBC',
    powerUnit: 'Ferrari',
    firstTeamEntry: 1993,
    worldChampionships: 0,
    highestRaceFinish: '1 (x1)',
    polePositions: 1,
    fastestLaps: 7,
  },
  {
    id: 10,
    identifier: 'RacingBulls',
    name: 'Racing Bulls',
    fullName: 'Visa Cash App Racing Bulls F1 Team',
    base: 'Faenza, Italy',
    flag: 'it',
    teamChief: 'Laurent Mekies',
    technicalChief: 'Jody Egginton',
    chassis: 'TBC',
    powerUnit: 'Honda RBPT',
    firstTeamEntry: 2024,
    worldChampionships: 0,
    highestRaceFinish: '0',
    polePositions: 1,
    fastestLaps: 4,
  },
  {
    id: 11,
    identifier: 'AlphaTauri',
    name: 'Alpha Tauri',
    fullName: 'Scuderia Alpha Tauri',
    base: 'Faenza, Italy',
    flag: 'it',
    teamChief: 'Franz Tost',
    technicalChief: 'Jody Egginton',
    chassis: 'AT03',
    powerUnit: 'Honda',
    firstTeamEntry: 2006,
    worldChampionships: 0,
    highestRaceFinish: '1 (x2)',
    polePositions: 1,
    fastestLaps: 5,
  },
  {
    id: 12,
    identifier: 'AlfaRomeo',
    name: 'Alfa Romeo',
    fullName: 'Alfa Romeo Racing Orlen',
    base: 'Hinwil, Switzerland',
    flag: 'ch',
    teamChief: 'Frédéric Vasseur',
    technicalChief: 'Jan Monchaux',
    chassis: 'C42',
    powerUnit: 'Ferrari',
    firstTeamEntry: 2019,
    worldChampionships: 0,
    highestRaceFinish: '0',
    polePositions: 12,
    fastestLaps: 15,
  },
  {
    id: 13,
    identifier: 'Lotus',
    name: 'Lotus',
    fullName: 'Team Lotus',
    base: 'Hethel, United Kingdom',
    flag: 'gb',
    teamChief: 'Gerard Lopez',
    technicalChief: 'Nick Chester',
    chassis: 'E23 Hybrid',
    powerUnit: 'Mercedes',
    firstTeamEntry: 1952,
    worldChampionships: 7,
    highestRaceFinish: '1 (x81)',
    polePositions: 107,
    fastestLaps: 71,
  },
  {
    id: 14,
    identifier: 'Renault',
    name: 'Renault',
    fullName: 'Renault DP World F1 Team',
    base: 'Enstone, United Kingdom',
    flag: 'gb',
    teamChief: 'Cyril Abiteboul',
    technicalChief: 'Rémi Taffin',
    chassis: 'R.S.20',
    powerUnit: 'Renault',
    firstTeamEntry: 1977,
    worldChampionships: 2,
    highestRaceFinish: '1 (x35)',
    polePositions: 51,
    fastestLaps: 31,
  },
];
