import { PointsSystem } from '../../interfaces';

export const POINT_SYSTEM_HEADER: PointsSystem = {
  position: 'Position',
  pointsByEra1: '1950-1959',
  pointsByEra2: '1960',
  pointsByEra3: '1961-1990',
  pointsByEra4: '1991-2002',
  pointsByEra5: '2003-2009',
  pointsByEra6: '2010-2025',
};

export const POINT_SYSTEM: PointsSystem[] = [
  {
    position: 1,
    pointsByEra1: '8',
    pointsByEra2: '8',
    pointsByEra3: '9',
    pointsByEra4: '10',
    pointsByEra5: '10',
    pointsByEra6: '25',
  },
  {
    position: 2,
    pointsByEra1: '6',
    pointsByEra2: '6',
    pointsByEra3: '6',
    pointsByEra4: '6',
    pointsByEra5: '8',
    pointsByEra6: '18',
  },
  {
    position: 3,
    pointsByEra1: '4',
    pointsByEra2: '4',
    pointsByEra3: '4',
    pointsByEra4: '4',
    pointsByEra5: '6',
    pointsByEra6: '15',
  },
  {
    position: 4,
    pointsByEra1: '3',
    pointsByEra2: '3',
    pointsByEra3: '3',
    pointsByEra4: '3',
    pointsByEra5: '5',
    pointsByEra6: '12',
  },
  {
    position: 5,
    pointsByEra1: '2',
    pointsByEra2: '2',
    pointsByEra3: '2',
    pointsByEra4: '2',
    pointsByEra5: '4',
    pointsByEra6: '10',
  },
  {
    position: 6,
    pointsByEra1: '0',
    pointsByEra2: '1',
    pointsByEra3: '1',
    pointsByEra4: '1',
    pointsByEra5: '3',
    pointsByEra6: '8',
  },
  {
    position: 7,
    pointsByEra1: '0',
    pointsByEra2: '0',
    pointsByEra3: '0',
    pointsByEra4: '0',
    pointsByEra5: '2',
    pointsByEra6: '6',
  },
  {
    position: 8,
    pointsByEra1: '0',
    pointsByEra2: '0',
    pointsByEra3: '0',
    pointsByEra4: '0',
    pointsByEra5: '1',
    pointsByEra6: '4',
  },
  {
    position: 9,
    pointsByEra1: '0',
    pointsByEra2: '0',
    pointsByEra3: '0',
    pointsByEra4: '0',
    pointsByEra5: '0',
    pointsByEra6: '2',
  },
  {
    position: 10,
    pointsByEra1: '0',
    pointsByEra2: '0',
    pointsByEra3: '0',
    pointsByEra4: '0',
    pointsByEra5: '0',
    pointsByEra6: '1',
  },
];
