import { F1_Team } from '../../interfaces';

export const F1_TEAMS: F1_Team[] = [
  {
    id: 1,
    name: 'Ferrari',
    originCountry: 'Italy',
    originCountryFlag: 'it',
    headquarters: 'Maranello, Italy',
    headquartersFlag: 'it',
    foundedYear: 1950,
    grandPrixWins: 242,
    constructorChampionships: 16,
  },
  {
    id: 2,
    name: 'McLaren',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Woking, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1963,
    grandPrixWins: 183,
    constructorChampionships: 8,
  },
  {
    id: 3,
    name: 'Mercedes',
    originCountry: 'Germany',
    originCountryFlag: 'de',
    headquarters: 'Brackley, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1954,
    grandPrixWins: 125,
    constructorChampionships: 8,
  },
  {
    id: 4,
    name: 'Red Bull Racing',
    originCountry: 'Austria',
    originCountryFlag: 'at',
    headquarters: 'Milton Keynes, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 2005,
    grandPrixWins: 92,
    constructorChampionships: 5,
  },
  {
    id: 5,
    name: 'Williams',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Grove, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 1977,
    grandPrixWins: 114,
    constructorChampionships: 9,
  },
  {
    id: 6,
    name: 'Alpine',
    originCountry: 'France',
    originCountryFlag: 'fr',
    headquarters: 'Enstone, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 2021,
    grandPrixWins: 0,
    constructorChampionships: 0,
  },
  {
    id: 7,
    name: 'Aston Martin',
    originCountry: 'United Kingdom',
    originCountryFlag: 'gb',
    headquarters: 'Silverstone, United Kingdom',
    headquartersFlag: 'gb',
    foundedYear: 2021,
    grandPrixWins: 0,
    constructorChampionships: 0,
  },
  {
    id: 8,
    name: 'Haas',
    originCountry: 'United States',
    originCountryFlag: 'us',
    headquarters: 'Kannapolis, United States',
    headquartersFlag: 'us',
    foundedYear: 2016,
    grandPrixWins: 0,
    constructorChampionships: 0,
  },
  {
    id: 9,
    name: 'Kick Sauber',
    originCountry: 'Switzerland',
    originCountryFlag: 'ch',
    headquarters: 'Hinwil, Switzerland',
    headquartersFlag: 'ch',
    foundedYear: 1993,
    grandPrixWins: 1,
    constructorChampionships: 0,
  },
  {
    id: 10,
    name: 'Racing Bulls',
    originCountry: 'Italy',
    originCountryFlag: 'it',
    headquarters: 'Faenza, Italy',
    headquartersFlag: 'it',
    foundedYear: 2024,
    grandPrixWins: 0,
    constructorChampionships: 0,
  },
];
